name: Update Demo Data

on:
  push:
  schedule:
    #        ?????????????? minute (0 - 59)
    #        ?  ?????????????? hour (0 - 23)
    #        ?  ? ?????????????? day of the month (1 - 31)
    #        ?  ? ? ?????????????? month (1 - 12 or JAN-DEC)
    #        ?  ? ? ? ?????????????? day of the week (0 - 6 or SUN-SAT)
    #        ?  ? ? ? ?
    #        ?  ? ? ? ?
    #        ?  ? ? ? ?
    #        *  * * * *
    # At 00:00 UTC on Sundays
    - cron: "0 0 * * 0"

  # Workflow dispatch trigger allows manually running workflow
  workflow_dispatch: {}

jobs:
  update-demo-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up local Git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install underscore library
        run: npm install underscore

      - name: Run the update script
        run: bash ./update_demo_data.sh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
